-- Model Registry Table
-- Task 3.10: Model Versioning and Performance Tracking
-- Stores metadata about trained models for versioning and tracking

CREATE TABLE OML.MODEL_REGISTRY (
    MODEL_ID VARCHAR2(50) PRIMARY KEY,
    MODEL_NAME VARCHAR2(100) NOT NULL,
    MODEL_VERSION VARCHAR2(50) NOT NULL,
    MODEL_TYPE VARCHAR2(50) NOT NULL,
    MODEL_FILE_PATH VARCHAR2(500) NOT NULL,
    METADATA_FILE_PATH VARCHAR2(500),
    
    -- Performance Metrics
    AUC_SCORE NUMBER(5,4),
    ACCURACY NUMBER(5,4),
    PRECISION_SCORE NUMBER(5,4),
    RECALL_SCORE NUMBER(5,4),
    F1_SCORE NUMBER(5,4),
    OPTIMAL_THRESHOLD NUMBER(5,4),
    
    -- Training Information
    TRAINING_DATE TIMESTAMP NOT NULL,
    TRAINING_DURATION_SECONDS NUMBER(10,2),
    TRAIN_SAMPLES NUMBER(10),
    TEST_SAMPLES NUMBER(10),
    FEATURE_COUNT NUMBER(5),
    
    -- Model Status
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE', 'DEPRECATED', 'ARCHIVED')),
    IS_PRODUCTION NUMBER(1) DEFAULT 0 CHECK (IS_PRODUCTION IN (0, 1)),
    
    -- Metadata
    TRAINING_PARAMETERS CLOB,
    NOTES VARCHAR2(1000),
    
    -- Timestamps
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes
CREATE INDEX IDX_MODEL_REGISTRY_NAME ON OML.MODEL_REGISTRY(MODEL_NAME);
CREATE INDEX IDX_MODEL_REGISTRY_VERSION ON OML.MODEL_REGISTRY(MODEL_VERSION);
CREATE INDEX IDX_MODEL_REGISTRY_STATUS ON OML.MODEL_REGISTRY(STATUS);
CREATE INDEX IDX_MODEL_REGISTRY_PRODUCTION ON OML.MODEL_REGISTRY(IS_PRODUCTION);
CREATE INDEX IDX_MODEL_REGISTRY_DATE ON OML.MODEL_REGISTRY(TRAINING_DATE);

-- Comments
COMMENT ON TABLE OML.MODEL_REGISTRY IS 'Registry of all trained churn prediction models for versioning and tracking';
COMMENT ON COLUMN OML.MODEL_REGISTRY.MODEL_ID IS 'Unique identifier for the model (timestamp-based)';
COMMENT ON COLUMN OML.MODEL_REGISTRY.MODEL_NAME IS 'Name of the model (e.g., XGBoost, CatBoost)';
COMMENT ON COLUMN OML.MODEL_REGISTRY.MODEL_VERSION IS 'Version identifier (e.g., v1.0, 20260118_184459)';
COMMENT ON COLUMN OML.MODEL_REGISTRY.MODEL_TYPE IS 'Type of model (e.g., XGBoost, CatBoost, RandomForest)';
COMMENT ON COLUMN OML.MODEL_REGISTRY.MODEL_FILE_PATH IS 'Path to the model pickle file';
COMMENT ON COLUMN OML.MODEL_REGISTRY.METADATA_FILE_PATH IS 'Path to the metadata JSON file';
COMMENT ON COLUMN OML.MODEL_REGISTRY.AUC_SCORE IS 'Area Under Curve (ROC) score';
COMMENT ON COLUMN OML.MODEL_REGISTRY.ACCURACY IS 'Model accuracy score';
COMMENT ON COLUMN OML.MODEL_REGISTRY.PRECISION_SCORE IS 'Model precision score';
COMMENT ON COLUMN OML.MODEL_REGISTRY.RECALL_SCORE IS 'Model recall score';
COMMENT ON COLUMN OML.MODEL_REGISTRY.F1_SCORE IS 'Model F1 score';
COMMENT ON COLUMN OML.MODEL_REGISTRY.OPTIMAL_THRESHOLD IS 'Optimal probability threshold for classification';
COMMENT ON COLUMN OML.MODEL_REGISTRY.TRAINING_DATE IS 'Date and time when model was trained';
COMMENT ON COLUMN OML.MODEL_REGISTRY.TRAINING_DURATION_SECONDS IS 'Time taken to train the model (seconds)';
COMMENT ON COLUMN OML.MODEL_REGISTRY.TRAIN_SAMPLES IS 'Number of training samples';
COMMENT ON COLUMN OML.MODEL_REGISTRY.TEST_SAMPLES IS 'Number of test samples';
COMMENT ON COLUMN OML.MODEL_REGISTRY.FEATURE_COUNT IS 'Number of features used';
COMMENT ON COLUMN OML.MODEL_REGISTRY.STATUS IS 'Model status: ACTIVE, DEPRECATED, ARCHIVED';
COMMENT ON COLUMN OML.MODEL_REGISTRY.IS_PRODUCTION IS 'Flag indicating if this is the production model (1) or not (0)';
COMMENT ON COLUMN OML.MODEL_REGISTRY.TRAINING_PARAMETERS IS 'JSON string of training hyperparameters';
COMMENT ON COLUMN OML.MODEL_REGISTRY.NOTES IS 'Additional notes about the model';
